[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_ENABLE_LOGGING = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200 